apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /node-akka-mgmt
            pathType: Prefix
            backend:
              service:
                name: node
                port:
                  number: 8558