---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node
  namespace: poc
spec:
  replicas: 2
#  selector:
#     matchLabels:
#       app: ArtifactStateCluster
  template:
    metadata:
      labels:
        app: ArtifactStateCluster
        tag: clusternode
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: node
        image: akka-typed-blog-distributed-state/cluster:0.1.0
        imagePullPolicy: IfNotPresent
        #health
        livenessProbe:
          httpGet:
            path: /alive
            port: akka-mgmt-http
        readinessProbe:
          httpGet:
            path: /ready
            port: akka-mgmt-http
        #health
        env:
        - name: HOSTNAME
          valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        - name: CASSANDRA_CONTACT_POINT1
          value: cassandra-peers
        - name: JAVA_OPTS
          value: "-Dconfig.resource=cluster-application-k8s.conf"
        ports:
        # akka remoting
        - name: remoting
          containerPort: 2552
          protocol: TCP
        # external http
        - name: akka-mgmt-http
          containerPort: 8558
          protocol: TCP
        - name: node-metrics
          containerPort: 9001

      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: poc
spec:
  type: NodePort
  ports:
  - name: akka-mgmt-http
    protocol: TCP
    port: 8558
    targetPort: akka-mgmt-http
    nodePort: 30558
  selector:
    tag: clusternode

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-reader
  namespace: poc

rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-nodes
  namespace: poc
subjects:
# Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
# For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
- kind: User
  name: system:serviceaccount:poc:default
roleRef:
  kind: Role
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
