---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endpoint
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ArtifactStateCluster
        tag: endpoint
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - env:
        - name: CASSANDRA_CONTACT_POINT1
          value: cassandra-peers
        - name: CLUSTER_IP
          value: endpoint
        - name: CLUSTER_PORT
          value: "1601"
        - name: SEED_PORT_1600_TCP_ADDR
          value: seed
        - name: JAVA_OPTS
          value: "-Dconfig.resource=endpoint-application-k8s.conf"
        image: image-registry.openshift-image-registry.svc:5000/poc/cluster:latest
        imagePullPolicy: IfNotPresent
        #health
        livenessProbe:
          httpGet:
            path: /alive
            port: akka-mgmt-http
        readinessProbe:
          httpGet:
            path: /ready
            port: akka-mgmt-http
        #health
        name: endpoint
        ports:
        - containerPort: 8082
        # akka remoting
        - name: remoting
          containerPort: 2552
          protocol: TCP
        # external http
        - name: akka-mgmt-http
          containerPort: 8558
          protocol: TCP
        - name: ep-metrics
          containerPort: 9001

        resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: endpoint
  namespace: poc
spec:
  type: NodePort
  ports:
  - name: "8082"
    protocol: TCP
    port: 8082
    targetPort: 8082
    nodePort: 30082
  selector:
    tag: endpoint

---
#
# Create a role, `endpoint-reader`, that can list pods and
# bind the default service account in the `default` namespace
# to that role.
#

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-reader
  namespace: poc
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-endpoints
  namespace: poc
subjects:
# Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
# For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
- kind: User
  name: system:serviceaccount:poc:default
roleRef:
  kind: Role
  name: endpoint-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: endpoint-route
  namespace: poc
spec:
  port:
    targetPort: '8082'
  to:
    kind: Service
    name: endpoint
    weight: 100
  wildcardPolicy: None
