apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endpoint
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: endpoint
        tag: endpoint
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9001'
    spec:
      serviceAccountName: endpoints-sa
      containers:
      - env:
        - name: APP-VERSION
          value: "0.1.21"
        - name: DATA-CENTER
          value: "dc1"
        - name: ALL-DATA-CENTERS
          value: "dc1,dc2"
        - name: QUERY_PLUGIN_ID
          value: "akka.persistence.r2dbc.query"
        - name: JAVA_OPTS
          value: "-Dconfig.resource=endpoint-application-k8s-multi-dc.conf"
        - name: JAVA_TOOL_OPTIONS
          value: "-Dconfig.resource=endpoint-application-k8s-multi-dc.conf"
        image: localhost:32000/akka-typed-blog-distributed-state/cluster:latest
        #health
        readinessProbe:
          httpGet:
            path: /ready
            port: akka-mgmt-http
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /alive
            port: akka-mgmt-http
          initialDelaySeconds: 90
          periodSeconds: 30
        #health
        name: endpoint
        ports:
        - containerPort: 8082
        # akka remoting
        - name: remoting
          containerPort: 2552
          protocol: TCP
        # external http
        - name: akka-mgmt-http
          containerPort: 8558
          protocol: TCP
        - name: node-metrics
          containerPort: 9001
        resources: {}
      restartPolicy: Always
status: {}
